# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metal_type', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('C', 'Copper')], max_length=1)),
                ('year_of_mintage', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
