# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sovereign_box', '0003_remove_cointag_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tags', to='sovereign_box.Coins')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sovereign_box.CoinTag')),
            ],
        ),
        migrations.AddField(
            model_name='coins',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_coin', through='sovereign_box.CoinTagLink', to='sovereign_box.CoinTag'),
        ),
    ]
