# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sovereign_box', '0005_auto_20191024_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='tags',
            field=models.ManyToManyField(blank=True, through='sovereign_box.CoinTagLink', to='sovereign_box.CoinTag'),
        ),
        migrations.AlterField(
            model_name='cointaglink',
            name='coins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sovereign_box.Coins'),
        ),
    ]
