# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-31 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovereign_box', '0006_auto_20191024_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
