# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-02 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovereign_box', '0008_auto_20191102_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='image_url_2',
        ),
        migrations.AddField(
            model_name='coins',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='image_file/%Y/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='coins',
            name='image_url_2',
            field=models.FileField(blank=True, null=True, upload_to='image_file/%Y/', verbose_name='Image'),
        ),
    ]
